Side effects should be last
arcanis/eslint-plugin-arca pull request #25
Opened 2021-07-05 08:13 UTC by Ayc0

2021-07-05 11:05 UTC, Ayc0 commented
@arcanis I detailed more this issue here: https://codesandbox.io/s/arca-side-effects-highlight-66ov5

2021-07-05 11:16 UTC, arcanis requested changes
We can't just switch the order - many imports (polyfills, global styles) need to be executed before anything else. Ideally we would have a way to define a module subset that, when imported this way, should be put last.

2021-07-05 13:17 UTC, Ayc0 commented
@arcanis I updated the code so that it considers the global and local side effects differently

2021-07-09 09:18 UTC, merged

2021-07-09 09:18 UTC, arcanis commented
Thanks!